public class Demo_Subs {
    public integer a;
    public integer b;
    public integer c;
    
    public integer subt(){
        // this is for revert 5
        c=a-b; 
        System.debug('this is test 4');
       	system.debug('Test 2');
        
        
        
        
        system.debug('the result is7'+c);
        system.debug('the result is8'+c);
        system.debug('the result is5'+c);
        system.debug('the result is2'+c);
       system.debug('the result is'+c);
        system.debug('the result is'+c);
        system.debug('the result is'+c);
        system.debug('the result is'+c);
        return c;
    }
    
    public Integer divt(){
        c=a/b;
        system.debug('the result is'+c);
        return c;
    }   
    
}