public class Movie {

    @AuraEnabled public String title { get; set; }
    @AuraEnabled public String year { get; set; }
    @AuraEnabled public String poster { get; set; }
    @AuraEnabled public String imdbId { get; set; }
    @AuraEnabled public String genre { get; set; }
    @AuraEnabled public String plot { get; set; }
    @AuraEnabled public String country { get; set; }
    //System.debug('this is test 5');
    ////System.debug('this is test 6');
    //  ////System.debug('this is test 7');
    //  test for revert commit
    //  //  test for revert commi

}