<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>AW_Case_Auto_Response</fullName>
        <description>AW - Case Auto Response</description>
        <protected>false</protected>
        <recipients>
            <field>ContactEmail</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>anchorwallace@anchorwallace.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Service_AW_Bounce_Back_Message</template>
    </alerts>
    <alerts>
        <fullName>CCC_Case_Auto_Response</fullName>
        <description>CCC - Case Auto Response</description>
        <protected>false</protected>
        <recipients>
            <field>ContactEmail</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>csinfo@calendarcs.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Service_CCC_Bounce_Back_Message</template>
    </alerts>
    <alerts>
        <fullName>Case_Auto_Response</fullName>
        <description>Case Auto Response</description>
        <protected>false</protected>
        <recipients>
            <field>ContactEmail</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>SuppliedEmail</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@kooziegroup.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Service_Bounce_Back_Message</template>
    </alerts>
    <alerts>
        <fullName>Clarification_Email</fullName>
        <description>Clarification Email</description>
        <protected>false</protected>
        <recipients>
            <field>Clarification_CC_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>Clarification_To_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@kooziegroup.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Clarification_Template</template>
    </alerts>
    <alerts>
        <fullName>Clarification_Email_2</fullName>
        <description>Clarification Email 2 - Case Escalation</description>
        <protected>false</protected>
        <recipients>
            <recipient>betty.jensen@kooziegroup.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>marlin.glenn@kooziegroup.com</recipient>
            <type>user</type>
        </recipients>
        <senderAddress>customerservice@kooziegroup.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Clarification_Template</template>
    </alerts>
    <alerts>
        <fullName>Greater_than_5k_Email_Alert</fullName>
        <ccEmails>InsideSales@kooziegroup.com</ccEmails>
        <description>Greater than 5k Email Alert - Use by Flow</description>
        <protected>false</protected>
        <senderType>CurrentUser</senderType>
        <template>Automation_Templates/Greater_than_5k</template>
    </alerts>
    <alerts>
        <fullName>ProofEmail</fullName>
        <description>ProofEmail</description>
        <protected>false</protected>
        <recipients>
            <field>Proof_CC_Email__c</field>
            <type>email</type>
        </recipients>
        <recipients>
            <field>Proof_To_Email__c</field>
            <type>email</type>
        </recipients>
        <senderAddress>customerservice@kooziegroup.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Proof_Template</template>
    </alerts>
    <alerts>
        <fullName>Proof_Email_2</fullName>
        <description>Proof Email 2 - Case Escalation</description>
        <protected>false</protected>
        <recipients>
            <recipient>betty.jensen@kooziegroup.com</recipient>
            <type>user</type>
        </recipients>
        <recipients>
            <recipient>marlin.glenn@kooziegroup.com</recipient>
            <type>user</type>
        </recipients>
        <senderAddress>customerservice@kooziegroup.com</senderAddress>
        <senderType>OrgWideEmailAddress</senderType>
        <template>Service_Templates/Proof_Template</template>
    </alerts>
    <alerts>
        <fullName>Send_reminder_for_large_orders</fullName>
        <description>Send reminder</description>
        <protected>false</protected>
        <recipients>
            <type>owner</type>
        </recipients>
        <senderType>DefaultWorkflowUser</senderType>
        <template>unfiled$public/Alerts_for_Large_Orders</template>
    </alerts>
</Workflow>
