<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>new_email_alerts</fullName>
        <description>new_email_alerts</description>
        <protected>false</protected>
        <recipients>
            <field>Email__c</field>
            <type>email</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/temp1</template>
    </alerts>
    <fieldUpdates>
        <fullName>updated_capital</fullName>
        <field>Capital__c</field>
        <literalValue>Patna</literalValue>
        <name>updated_capital</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <rules>
        <fullName>capital_matching</fullName>
        <actions>
            <name>updated_capital</name>
            <type>FieldUpdate</type>
        </actions>
        <active>true</active>
        <criteriaItems>
            <field>Employee__c.State__c</field>
            <operation>equals</operation>
            <value>Bihar</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
