<?xml version="1.0" encoding="UTF-8"?>
<Workflow xmlns="http://soap.sforce.com/2006/04/metadata">
    <alerts>
        <fullName>abcd</fullName>
        <description>email field update</description>
        <protected>false</protected>
        <recipients>
            <recipient>vikash.semykolon@gmail.com</recipient>
            <type>user</type>
        </recipients>
        <senderType>CurrentUser</senderType>
        <template>unfiled$public/SalesNewCustomerEmail</template>
    </alerts>
    <fieldUpdates>
        <fullName>approved</fullName>
        <field>status__c</field>
        <literalValue>approved</literalValue>
        <name>approved</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>in_progress</fullName>
        <field>status__c</field>
        <literalValue>in progress</literalValue>
        <name>in progress</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>rejected</fullName>
        <field>status__c</field>
        <literalValue>rejected</literalValue>
        <name>rejected</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>text</fullName>
        <field>state__c</field>
        <literalValue>DELHI</literalValue>
        <name>text</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>update_city</fullName>
        <field>CITY__c</field>
        <literalValue>HAPUR</literalValue>
        <name>update city</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <fieldUpdates>
        <fullName>update_state</fullName>
        <field>state__c</field>
        <literalValue>DELHI</literalValue>
        <name>update state</name>
        <notifyAssignee>false</notifyAssignee>
        <operation>Literal</operation>
        <protected>false</protected>
        <reevaluateOnChange>false</reevaluateOnChange>
    </fieldUpdates>
    <rules>
        <fullName>update capital field</fullName>
        <actions>
            <name>update_city</name>
            <type>FieldUpdate</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>student__c.state__c</field>
            <operation>equals</operation>
            <value>UP</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
    <rules>
        <fullName>update email field update</fullName>
        <actions>
            <name>abcd</name>
            <type>Alert</type>
        </actions>
        <active>false</active>
        <criteriaItems>
            <field>student__c.email__c</field>
            <operation>notEqual</operation>
            <value>non</value>
        </criteriaItems>
        <triggerType>onCreateOrTriggeringUpdate</triggerType>
    </rules>
</Workflow>
